package com.frauddetection.flink.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.Instant;

/**
 * Fraud alert generated by the real-time processing engine.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class FraudAlertEvent implements Serializable {

    private String alertId;
    private String transactionId;
    private String userId;
    private String reason;
    private double score;
    private BigDecimal transactionAmount;
    private BigDecimal windowTotal;
    private String merchantId;
    private String location;
    private Instant detectedAt;
    private String severity;

    public FraudAlertEvent() {}

    public String getAlertId() { return alertId; }
    public void setAlertId(String alertId) { this.alertId = alertId; }
    public String getTransactionId() { return transactionId; }
    public void setTransactionId(String transactionId) { this.transactionId = transactionId; }
    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }
    public String getReason() { return reason; }
    public void setReason(String reason) { this.reason = reason; }
    public double getScore() { return score; }
    public void setScore(double score) { this.score = score; }
    public BigDecimal getTransactionAmount() { return transactionAmount; }
    public void setTransactionAmount(BigDecimal transactionAmount) { this.transactionAmount = transactionAmount; }
    public BigDecimal getWindowTotal() { return windowTotal; }
    public void setWindowTotal(BigDecimal windowTotal) { this.windowTotal = windowTotal; }
    public String getMerchantId() { return merchantId; }
    public void setMerchantId(String merchantId) { this.merchantId = merchantId; }
    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }
    public Instant getDetectedAt() { return detectedAt; }
    public void setDetectedAt(Instant detectedAt) { this.detectedAt = detectedAt; }
    public String getSeverity() { return severity; }
    public void setSeverity(String severity) { this.severity = severity; }

    @Override
    public String toString() {
        return "FraudAlertEvent{alertId='" + alertId + "', userId='" + userId +
                "', reason='" + reason + "', score=" + score + ", severity='" + severity + "'}";
    }
}
