package com.frauddetection.alert.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Represents a fraud alert generated by the real-time processing engine.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class FraudAlert {

    private String alertId;
    private String transactionId;
    private String userId;
    private String reason;
    private double score;
    private BigDecimal transactionAmount;
    private BigDecimal windowTotal;
    private String merchantId;
    private String location;
    private Instant detectedAt;
    private String severity;
}
